export default {

  template: `
    <p class="background-text"  v-typing="{ char: '01', amount: 0, speed: 1200 }">
    {{ date.year }}  {{ date.time }}    DIR          . |
    {{ date.year }}  {{ date.time }}    DIR          .. |
    {{ date.year }}  {{ date.time }}            12 189 accessor-pairs.js |
    {{ date.year }}  {{ date.time }}             9 590 array-bracket-newline.js |
    {{ date.year }}  {{ date.time }}             9 081 array-bracket-spacing.js |
    {{ date.year }}  {{ date.time }}             9 811 array-callback-return.js |
    {{ date.year }}  {{ date.time }}            10 959 array-element-newline.js |
    {{ date.year }}  {{ date.time }}            12 963 arrow-body-style.js |
    {{ date.year }}  {{ date.time }}             7 704 arrow-parens.js |
    {{ date.year }}  {{ date.time }}             5 202 arrow-spacing.js |
    {{ date.year }}  {{ date.time }}             3 660 block-scoped-var.js |
    {{ date.year }}  {{ date.time }}             5 576 block-spacing.js |
    {{ date.year }}  {{ date.time }}             7 897 brace-style.js |
    {{ date.year }}  {{ date.time }}             6 540 callback-return.js |
    {{ date.year }}  {{ date.time }}            12 492 camelcase.js |
    {{ date.year }}  {{ date.time }}            10 733 capitalized-comments.js |
    {{ date.year }}  {{ date.time }}             3 900 class-methods-use-this.js |
    {{ date.year }}  {{ date.time }}            12 383 comma-dangle.js |
    {{ date.year }}  {{ date.time }}             6 678 comma-spacing.js |
    {{ date.year }}  {{ date.time }}            11 917 comma-style.js |
    {{ date.year }}  {{ date.time }}             5 270 complexity.js |
    {{ date.year }}  {{ date.time }}             7 493 computed-property-spacing.js |
    {{ date.year }}  {{ date.time }}             6 393 consistent-return.js |
    {{ date.year }}  {{ date.time }}             4 969 consistent-this.js |
    {{ date.year }}  {{ date.time }}            15 018 constructor-super.js |
    {{ date.year }}  {{ date.time }}            19 379 curly.js |
    {{ date.year }}  {{ date.time }}             1 230 default-case-last.js |
    {{ date.year }}  {{ date.time }}             2 830 default-case.js |
    {{ date.year }}  {{ date.time }}             1 599 default-param-last.js |
    {{ date.year }}  {{ date.time }}             3 420 dot-location.js |
    {{ date.year }}  {{ date.time }}             6 762 dot-notation.js |
    {{ date.year }}  {{ date.time }}             3 720 eol-last.js |
    {{ date.year }}  {{ date.time }}             5 776 eqeqeq.js |
    {{ date.year }}  {{ date.time }}             4 377 for-direction.js |
    {{ date.year }}  {{ date.time }}             9 918 func-call-spacing.js |
    {{ date.year }}  {{ date.time }}            10 052 func-name-matching.js |
    {{ date.year }}  {{ date.time }}             6 364 func-names.js |
    {{ date.year }}  {{ date.time }}             2 912 func-style.js |
    {{ date.year }}  {{ date.time }}             4 325 function-call-argument-newline.js |
    {{ date.year }}  {{ date.time }}            11 451 function-paren-newline.js |
    {{ date.year }}  {{ date.time }}             7 083 generator-star-spacing.js |
    {{ date.year }}  {{ date.time }}             5 937 getter-return.js |
    {{ date.year }}  {{ date.time }}             2 429 global-require.js |
    {{ date.year }}  {{ date.time }}             7 850 grouped-accessor-pairs.js |
    {{ date.year }}  {{ date.time }}             2 357 guard-for-in.js |
    {{ date.year }}  {{ date.time }}             3 039 handle-callback-err.js |
    {{ date.year }}  {{ date.time }}             7 106 id-blacklist.js |
    {{ date.year }}  {{ date.time }}             7 041 id-denylist.js |
    {{ date.year }}  {{ date.time }}             5 282 id-length.js |
    {{ date.year }}  {{ date.time }}             8 383 id-match.js |
    {{ date.year }}  {{ date.time }}             2 862 implicit-arrow-linebreak.js |
    {{ date.year }}  {{ date.time }}            44 641 indent-legacy.js |
    {{ date.year }}  {{ date.time }}            73 922 indent.js |
    {{ date.year }}  {{ date.time }}            17 725 index.js |
    {{ date.year }}  {{ date.time }}             4 467 init-declarations.js |
    {{ date.year }}  {{ date.time }}             2 960 jsx-quotes.js |
    {{ date.year }}  {{ date.time }}            26 384 key-spacing.js |
    {{ date.year }}  {{ date.time }}            21 634 keyword-spacing.js |
    {{ date.year }}  {{ date.time }}             4 180 line-comment-position.js |
    {{ date.year }}  {{ date.time }}             3 479 linebreak-style.js |
    {{ date.year }}  {{ date.time }}            15 861 lines-around-comment.js |
    {{ date.year }}  {{ date.time }}             7 761 lines-around-directive.js |
    {{ date.year }}  {{ date.time }}             5 805 lines-between-class-members.js |
    {{ date.year }}  {{ date.time }}             1 776 max-classes-per-file.js |
    {{ date.year }}  {{ date.time }}             4 699 max-depth.js |
    {{ date.year }}  {{ date.time }}            16 037 max-len.js |
    {{ date.year }}  {{ date.time }}             7 082 max-lines-per-function.js |
    {{ date.year }}  {{ date.time }}             6 696 max-lines.js |
    {{ date.year }}  {{ date.time }}             3 551 max-nested-callbacks.js |
    {{ date.year }}  {{ date.time }}             3 169 max-params.js |
    {{ date.year }}  {{ date.time }}             7 436 max-statements-per-line.js |
    {{ date.year }}  {{ date.time }}             5 555 max-statements.js |
    {{ date.year }}  {{ date.time }}            20 533 multiline-comment-style.js |
    {{ date.year }}  {{ date.time }}             7 722 multiline-ternary.js |
    {{ date.year }}  {{ date.time }}             9 426 new-cap.js |
    {{ date.year }}  {{ date.time }}             3 441 new-parens.js |
    {{ date.year }}  {{ date.time }}             9 803 newline-after-var.js |
    {{ date.year }}  {{ date.time }}             8 053 newline-before-return.js |
    {{ date.year }}  {{ date.time }}             4 046 newline-per-chained-call.js |
    {{ date.year }}  {{ date.time }}             4 289 no-alert.js |
    {{ date.year }}  {{ date.time }}             1 395 no-array-constructor.js |
    {{ date.year }}  {{ date.time }}             1 130 no-async-promise-executor.js |
    {{ date.year }}  {{ date.time }}             2 781 no-await-in-loop.js |
    {{ date.year }}  {{ date.time }}             3 595 no-bitwise.js |
    {{ date.year }}  {{ date.time }}             1 391 no-buffer-constructor.js |
    {{ date.year }}  {{ date.time }}             1 194 no-caller.js |
    {{ date.year }}  {{ date.time }}             1 863 no-case-declarations.js |
    {{ date.year }}  {{ date.time }}             2 497 no-catch-shadow.js |
    {{ date.year }}  {{ date.time }}             1 701 no-class-assign.js |
    {{ date.year }}  {{ date.time }}             1 931 no-compare-neg-zero.js |
    {{ date.year }}  {{ date.time }}             5 650 no-cond-assign.js |
    {{ date.year }}  {{ date.time }}             2 611 no-confusing-arrow.js |
    {{ date.year }}  {{ date.time }}             4 262 no-console.js |
    {{ date.year }}  {{ date.time }}             1 489 no-const-assign.js |
    {{ date.year }}  {{ date.time }}            10 698 no-constant-condition.js |
    {{ date.year }}  {{ date.time }}             1 596 no-constructor-return.js |
    {{ date.year }}  {{ date.time }}               875 no-continue.js |
    {{ date.year }}  {{ date.time }}             3 178 no-control-regex.js |
    {{ date.year }}  {{ date.time }}               947 no-debugger.js |
    {{ date.year }}  {{ date.time }}               965 no-delete-var.js |
    {{ date.year }}  {{ date.time }}             1 454 no-div-regex.js |
    {{ date.year }}  {{ date.time }}             2 350 no-dupe-args.js |
    {{ date.year }}  {{ date.time }}             3 266 no-dupe-class-members.js |
    {{ date.year }}  {{ date.time }}             4 616 no-dupe-else-if.js |
    {{ date.year }}  {{ date.time }}             4 015 no-dupe-keys.js |
    {{ date.year }}  {{ date.time }}             2 080 no-duplicate-case.js |
    {{ date.year }}  {{ date.time }}             9 485 no-duplicate-imports.js |
    {{ date.year }}  {{ date.time }}            16 028 no-else-return.js |
    {{ date.year }}  {{ date.time }}             1 960 no-empty-character-class.js |
    {{ date.year }}  {{ date.time }}             4 741 no-empty-function.js |
    {{ date.year }}  {{ date.time }}             1 180 no-empty-pattern.js |
    {{ date.year }}  {{ date.time }}             2 501 no-empty.js |
    {{ date.year }}  {{ date.time }}             1 234 no-eq-null.js |
    {{ date.year }}  {{ date.time }}             8 879 no-eval.js |
    {{ date.year }}  {{ date.time }}             1 405 no-ex-assign.js |
    {{ date.year }}  {{ date.time }}             6 587 no-extend-native.js |
    {{ date.year }}  {{ date.time }}             7 564 no-extra-bind.js |
    {{ date.year }}  {{ date.time }}            11 926 no-extra-boolean-cast.js |
    {{ date.year }}  {{ date.time }}             5 153 no-extra-label.js |
    {{ date.year }}  {{ date.time }}            48 289 no-extra-parens.js |
    {{ date.year }}  {{ date.time }}             4 189 no-extra-semi.js |
    {{ date.year }}  {{ date.time }}             5 265 no-fallthrough.js |
    {{ date.year }}  {{ date.time }}             2 390 no-floating-decimal.js |
    {{ date.year }}  {{ date.time }}             2 193 no-func-assign.js |
    {{ date.year }}  {{ date.time }}             2 975 no-global-assign.js |
    {{ date.year }}  {{ date.time }}            12 358 no-implicit-coercion.js |
    {{ date.year }}  {{ date.time }}             5 360 no-implicit-globals.js |
    {{ date.year }}  {{ date.time }}             4 557 no-implied-eval.js |
    {{ date.year }}  {{ date.time }}             7 339 no-import-assign.js |
    {{ date.year }}  {{ date.time }}             3 363 no-inline-comments.js |
    {{ date.year }}  {{ date.time }}             2 497 no-inner-declarations.js |
    {{ date.year }}  {{ date.time }}             5 032 no-invalid-regexp.js |
    {{ date.year }}  {{ date.time }}             4 412 no-invalid-this.js |
    {{ date.year }}  {{ date.time }}             9 573 no-irregular-whitespace.js |
    {{ date.year }}  {{ date.time }}             1 295 no-iterator.js |
    {{ date.year }}  {{ date.time }}             2 345 no-label-var.js |
    {{ date.year }}  {{ date.time }}             4 494 no-labels.js |
    {{ date.year }}  {{ date.time }}             3 953 no-lone-blocks.js |
    {{ date.year }}  {{ date.time }}             3 796 no-lonely-if.js |
    {{ date.year }}  {{ date.time }}             6 269 no-loop-func.js |
    {{ date.year }}  {{ date.time }}             7 916 no-loss-of-precision.js |
    {{ date.year }}  {{ date.time }}             8 655 no-magic-numbers.js |
    {{ date.year }}  {{ date.time }}             6 387 no-misleading-character-class.js |
    {{ date.year }}  {{ date.time }}             7 687 no-mixed-operators.js |
    {{ date.year }}  {{ date.time }}             7 397 no-mixed-requires.js |
    {{ date.year }}  {{ date.time }}             3 667 no-mixed-spaces-and-tabs.js |
    {{ date.year }}  {{ date.time }}             1 741 no-multi-assign.js |
    {{ date.year }}  {{ date.time }}             5 079 no-multi-spaces.js |
    {{ date.year }}  {{ date.time }}             1 832 no-multi-str.js |
    {{ date.year }}  {{ date.time }}             6 309 no-multiple-empty-lines.js |
    {{ date.year }}  {{ date.time }}             2 999 no-native-reassign.js |
    {{ date.year }}  {{ date.time }}             2 958 no-negated-condition.js |
    {{ date.year }}  {{ date.time }}             1 173 no-negated-in-lhs.js |
    {{ date.year }}  {{ date.time }}             1 135 no-nested-ternary.js |
    {{ date.year }}  {{ date.time }}             1 671 no-new-func.js |
    {{ date.year }}  {{ date.time }}             1 564 no-new-object.js |
    {{ date.year }}  {{ date.time }}             1 155 no-new-require.js |
    {{ date.year }}  {{ date.time }}             1 535 no-new-symbol.js |
    {{ date.year }}  {{ date.time }}             1 224 no-new-wrappers.js |
    {{ date.year }}  {{ date.time }}             1 048 no-new.js |
    {{ date.year }}  {{ date.time }}             5 591 no-nonoctal-decimal-escape.js |
    {{ date.year }}  {{ date.time }}             2 648 no-obj-calls.js |
    {{ date.year }}  {{ date.time }}             1 463 no-octal-escape.js |
    {{ date.year }}  {{ date.time }}             1 021 no-octal.js |
    {{ date.year }}  {{ date.time }}             8 557 no-param-reassign.js |
    {{ date.year }}  {{ date.time }}             1 677 no-path-concat.js |
    {{ date.year }}  {{ date.time }}             3 164 no-plusplus.js |
    {{ date.year }}  {{ date.time }}             1 182 no-process-env.js |
    {{ date.year }}  {{ date.time }}             1 231 no-process-exit.js |
    {{ date.year }}  {{ date.time }}             3 623 no-promise-executor-return.js |
    {{ date.year }}  {{ date.time }}             1 227 no-proto.js |
    {{ date.year }}  {{ date.time }}             2 049 no-prototype-builtins.js |
    {{ date.year }}  {{ date.time }}             5 735 no-redeclare.js |
    {{ date.year }}  {{ date.time }}             6 070 no-regex-spaces.js |
    {{ date.year }}  {{ date.time }}             2 777 no-restricted-exports.js |
    {{ date.year }}  {{ date.time }}             3 760 no-restricted-globals.js |
    {{ date.year }}  {{ date.time }}            11 400 no-restricted-imports.js |
    {{ date.year }}  {{ date.time }}             7 044 no-restricted-modules.js |
    {{ date.year }}  {{ date.time }}             6 749 no-restricted-properties.js |
    {{ date.year }}  {{ date.time }}             2 162 no-restricted-syntax.js |
    {{ date.year }}  {{ date.time }}             2 679 no-return-assign.js |
    {{ date.year }}  {{ date.time }}             3 896 no-return-await.js |
    {{ date.year }}  {{ date.time }}             1 739 no-script-url.js |
    {{ date.year }}  {{ date.time }}             5 592 no-self-assign.js |
    {{ date.year }}  {{ date.time }}             1 846 no-self-compare.js |
    {{ date.year }}  {{ date.time }}             4 769 no-sequences.js |
    {{ date.year }}  {{ date.time }}             7 075 no-setter-return.js |
    {{ date.year }}  {{ date.time }}             2 144 no-shadow-restricted-names.js |
    {{ date.year }}  {{ date.time }}             8 233 no-shadow.js |
    {{ date.year }}  {{ date.time }}             2 477 no-spaced-func.js |
    {{ date.year }}  {{ date.time }}             1 187 no-sparse-arrays.js |
    {{ date.year }}  {{ date.time }}             1 670 no-sync.js |
    {{ date.year }}  {{ date.time }}             2 415 no-tabs.js |
    {{ date.year }}  {{ date.time }}             1 170 no-template-curly-in-string.js |
    {{ date.year }}  {{ date.time }}               878 no-ternary.js |
    {{ date.year }}  {{ date.time }}            10 227 no-this-before-super.js |
    {{ date.year }}  {{ date.time }}             1 293 no-throw-literal.js |
    {{ date.year }}  {{ date.time }}             6 793 no-trailing-spaces.js |
    {{ date.year }}  {{ date.time }}             2 388 no-undef-init.js |
    {{ date.year }}  {{ date.time }}             2 292 no-undef.js |
    {{ date.year }}  {{ date.time }}             2 212 no-undefined.js |
    {{ date.year }}  {{ date.time }}            10 460 no-underscore-dangle.js |
    {{ date.year }}  {{ date.time }}             4 283 no-unexpected-multiline.js |
    {{ date.year }}  {{ date.time }}            11 914 no-unmodified-loop-condition.js |
    {{ date.year }}  {{ date.time }}             6 949 no-unneeded-ternary.js |
    {{ date.year }}  {{ date.time }}             5 143 no-unreachable-loop.js |
    {{ date.year }}  {{ date.time }}             6 506 no-unreachable.js |
    {{ date.year }}  {{ date.time }}             3 992 no-unsafe-finally.js |
    {{ date.year }}  {{ date.time }}             4 728 no-unsafe-negation.js |
    {{ date.year }}  {{ date.time }}             7 122 no-unsafe-optional-chaining.js |
    {{ date.year }}  {{ date.time }}             6 244 no-unused-expressions.js |
    {{ date.year }}  {{ date.time }}             3 263 no-unused-labels.js |
    {{ date.year }}  {{ date.time }}            26 166 no-unused-vars.js |
    {{ date.year }}  {{ date.time }}             7 675 no-use-before-define.js |
    {{ date.year }}  {{ date.time }}             7 588 no-useless-backreference.js |
    {{ date.year }}  {{ date.time }}             3 049 no-useless-call.js |
    {{ date.year }}  {{ date.time }}             1 736 no-useless-catch.js |
    {{ date.year }}  {{ date.time }}             4 024 no-useless-computed-key.js |
    {{ date.year }}  {{ date.time }}             3 310 no-useless-concat.js |
    {{ date.year }}  {{ date.time }}             5 873 no-useless-constructor.js |
    {{ date.year }}  {{ date.time }}            10 037 no-useless-escape.js |
    {{ date.year }}  {{ date.time }}             5 879 no-useless-rename.js |
    {{ date.year }}  {{ date.time }}            12 153 no-useless-return.js |
    {{ date.year }}  {{ date.time }}            12 404 no-var.js |
    {{ date.year }}  {{ date.time }}             1 752 no-void.js |
    {{ date.year }}  {{ date.time }}             6 531 no-warning-comments.js |
    {{ date.year }}  {{ date.time }}             3 922 no-whitespace-before-property.js |
    {{ date.year }}  {{ date.time }}               863 no-with.js |
    {{ date.year }}  {{ date.time }}             4 577 nonblock-statement-body-position.js |
    {{ date.year }}  {{ date.time }}            11 715 object-curly-newline.js |
    {{ date.year }}  {{ date.time }}            11 813 object-curly-spacing.js |
    {{ date.year }}  {{ date.time }}             3 802 object-property-newline.js |
    {{ date.year }}  {{ date.time }}            21 657 object-shorthand.js |
    {{ date.year }}  {{ date.time }}             2 834 one-var-declaration-per-line.js |
    {{ date.year }}  {{ date.time }}            22 757 one-var.js |
    {{ date.year }}  {{ date.time }}             8 705 operator-assignment.js |
    {{ date.year }}  {{ date.time }}             9 858 operator-linebreak.js |
    {{ date.year }}  {{ date.time }}            10 633 padded-blocks.js |
    {{ date.year }}  {{ date.time }}            20 662 padding-line-between-statements.js |
    {{ date.year }}  {{ date.time }}            14 534 prefer-arrow-callback.js |
    {{ date.year }}  {{ date.time }}            18 064 prefer-const.js |
    {{ date.year }}  {{ date.time }}            11 074 prefer-destructuring.js |
    {{ date.year }}  {{ date.time }}             7 636 prefer-exponentiation-operator.js |
    {{ date.year }}  {{ date.time }}             3 421 prefer-named-capture-group.js |
    {{ date.year }}  {{ date.time }}             5 828 prefer-numeric-literals.js |
    {{ date.year }}  {{ date.time }}            10 686 prefer-object-spread.js |
    {{ date.year }}  {{ date.time }}             5 439 prefer-promise-reject-errors.js |
    {{ date.year }}  {{ date.time }}             4 693 prefer-reflect.js |
    {{ date.year }}  {{ date.time }}             6 748 prefer-regex-literals.js |
    {{ date.year }}  {{ date.time }}             3 349 prefer-rest-params.js |
    {{ date.year }}  {{ date.time }}             2 839 prefer-spread.js |
    {{ date.year }}  {{ date.time }}            11 445 prefer-template.js |
    {{ date.year }}  {{ date.time }}            12 034 quote-props.js |
    {{ date.year }}  {{ date.time }}            11 940 quotes.js |
    {{ date.year }}  {{ date.time }}             6 890 radix.js |
    {{ date.year }}  {{ date.time }}             9 819 require-atomic-updates.js |
    {{ date.year }}  {{ date.time }}             3 342 require-await.js |
    {{ date.year }}  {{ date.time }}             3 826 require-jsdoc.js |
    {{ date.year }}  {{ date.time }}             1 982 require-unicode-regexp.js |
    {{ date.year }}  {{ date.time }}             2 131 require-yield.js |
    {{ date.year }}  {{ date.time }}             4 035 rest-spread-spacing.js |
    {{ date.year }}  {{ date.time }}             8 784 semi-spacing.js |
    {{ date.year }}  {{ date.time }}             5 180 semi-style.js |
    {{ date.year }}  {{ date.time }}            12 084 semi.js |
    {{ date.year }}  {{ date.time }}            10 866 sort-imports.js |
    {{ date.year }}  {{ date.time }}             5 432 sort-keys.js |
    {{ date.year }}  {{ date.time }}             4 130 sort-vars.js |
    {{ date.year }}  {{ date.time }}             6 768 space-before-blocks.js |
    {{ date.year }}  {{ date.time }}             5 917 space-before-function-paren.js |
    {{ date.year }}  {{ date.time }}            10 711 space-in-parens.js |
    {{ date.year }}  {{ date.time }}             5 547 space-infix-ops.js |
    {{ date.year }}  {{ date.time }}            12 598 space-unary-ops.js |
    {{ date.year }}  {{ date.time }}            13 074 spaced-comment.js |
    {{ date.year }}  {{ date.time }}            10 549 strict.js |
    {{ date.year }}  {{ date.time }}             5 327 switch-colon-spacing.js |
    {{ date.year }}  {{ date.time }}             2 013 symbol-description.js |
    {{ date.year }}  {{ date.time }}             4 759 template-curly-spacing.js |
    {{ date.year }}  {{ date.time }}             3 067 template-tag-spacing.js |
    {{ date.year }}  {{ date.time }}             2 200 unicode-bom.js |
    {{ date.year }}  {{ date.time }}             4 741 use-isnan.js |
    {{ date.year }}  {{ date.time }}    DIR          utils |
    {{ date.year }}  {{ date.time }}            20 525 valid-jsdoc.js |
    {{ date.year }}  {{ date.time }}             3 043 valid-typeof.js |
    {{ date.year }}  {{ date.time }}             5 091 vars-on-top.js |
    {{ date.year }}  {{ date.time }}             7 883 wrap-iife.js |
    {{ date.year }}  {{ date.time }}             1 902 wrap-regex.js |
    {{ date.year }}  {{ date.time }}             4 320 yield-star-spacing.js |
    {{ date.year }}  {{ date.time }}            12 510 yoda.js |
                285 файлов      1 882 744 байт
  </p>
  `,

  computed: {

    date() {
      const d = new Date()
      return { year: d.toLocaleDateString('ru-Ru'), time: d.toLocaleTimeString('ru-Ru') }
    }

  },

}